# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.30

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jeffmur/dev/fhel

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jeffmur/dev/fhel

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jeffmur/dev/fhel/CMakeFiles /home/jeffmur/dev/fhel//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jeffmur/dev/fhel/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named fhel

# Build rule for target.
fhel: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fhel
.PHONY : fhel

# fast build rule for target.
fhel/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fhel.dir/build.make CMakeFiles/fhel.dir/build
.PHONY : fhel/fast

#=============================================================================
# Target rules for targets named seal

# Build rule for target.
seal: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 seal
.PHONY : seal

# fast build rule for target.
seal/fast:
	$(MAKE) $(MAKESILENT) -f src/backend/seal/CMakeFiles/seal.dir/build.make src/backend/seal/CMakeFiles/seal.dir/build
.PHONY : seal/fast

#=============================================================================
# Target rules for targets named sealc

# Build rule for target.
sealc: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sealc
.PHONY : sealc

# fast build rule for target.
sealc/fast:
	$(MAKE) $(MAKESILENT) -f src/backend/seal/CMakeFiles/sealc.dir/build.make src/backend/seal/CMakeFiles/sealc.dir/build
.PHONY : sealc/fast

#=============================================================================
# Target rules for targets named zlib

# Build rule for target.
zlib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zlib
.PHONY : zlib

# fast build rule for target.
zlib/fast:
	$(MAKE) $(MAKESILENT) -f src/backend/seal/thirdparty/zlib-build/CMakeFiles/zlib.dir/build.make src/backend/seal/thirdparty/zlib-build/CMakeFiles/zlib.dir/build
.PHONY : zlib/fast

#=============================================================================
# Target rules for targets named zlibstatic

# Build rule for target.
zlibstatic: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zlibstatic
.PHONY : zlibstatic

# fast build rule for target.
zlibstatic/fast:
	$(MAKE) $(MAKESILENT) -f src/backend/seal/thirdparty/zlib-build/CMakeFiles/zlibstatic.dir/build.make src/backend/seal/thirdparty/zlib-build/CMakeFiles/zlibstatic.dir/build
.PHONY : zlibstatic/fast

#=============================================================================
# Target rules for targets named example

# Build rule for target.
example: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 example
.PHONY : example

# fast build rule for target.
example/fast:
	$(MAKE) $(MAKESILENT) -f src/backend/seal/thirdparty/zlib-build/CMakeFiles/example.dir/build.make src/backend/seal/thirdparty/zlib-build/CMakeFiles/example.dir/build
.PHONY : example/fast

#=============================================================================
# Target rules for targets named minigzip

# Build rule for target.
minigzip: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 minigzip
.PHONY : minigzip

# fast build rule for target.
minigzip/fast:
	$(MAKE) $(MAKESILENT) -f src/backend/seal/thirdparty/zlib-build/CMakeFiles/minigzip.dir/build.make src/backend/seal/thirdparty/zlib-build/CMakeFiles/minigzip.dir/build
.PHONY : minigzip/fast

#=============================================================================
# Target rules for targets named example64

# Build rule for target.
example64: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 example64
.PHONY : example64

# fast build rule for target.
example64/fast:
	$(MAKE) $(MAKESILENT) -f src/backend/seal/thirdparty/zlib-build/CMakeFiles/example64.dir/build.make src/backend/seal/thirdparty/zlib-build/CMakeFiles/example64.dir/build
.PHONY : example64/fast

#=============================================================================
# Target rules for targets named minigzip64

# Build rule for target.
minigzip64: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 minigzip64
.PHONY : minigzip64

# fast build rule for target.
minigzip64/fast:
	$(MAKE) $(MAKESILENT) -f src/backend/seal/thirdparty/zlib-build/CMakeFiles/minigzip64.dir/build.make src/backend/seal/thirdparty/zlib-build/CMakeFiles/minigzip64.dir/build
.PHONY : minigzip64/fast

#=============================================================================
# Target rules for targets named clean-all

# Build rule for target.
clean-all: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean-all
.PHONY : clean-all

# fast build rule for target.
clean-all/fast:
	$(MAKE) $(MAKESILENT) -f src/backend/seal/thirdparty/zstd-build/CMakeFiles/clean-all.dir/build.make src/backend/seal/thirdparty/zstd-build/CMakeFiles/clean-all.dir/build
.PHONY : clean-all/fast

#=============================================================================
# Target rules for targets named libzstd_static

# Build rule for target.
libzstd_static: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libzstd_static
.PHONY : libzstd_static

# fast build rule for target.
libzstd_static/fast:
	$(MAKE) $(MAKESILENT) -f src/backend/seal/thirdparty/zstd-build/lib/CMakeFiles/libzstd_static.dir/build.make src/backend/seal/thirdparty/zstd-build/lib/CMakeFiles/libzstd_static.dir/build
.PHONY : libzstd_static/fast

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) $(MAKESILENT) -f src/backend/seal/thirdparty/zstd-build/lib/CMakeFiles/uninstall.dir/build.make src/backend/seal/thirdparty/zstd-build/lib/CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

src/backend/aseal.o: src/backend/aseal.cpp.o
.PHONY : src/backend/aseal.o

# target to build an object file
src/backend/aseal.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fhel.dir/build.make CMakeFiles/fhel.dir/src/backend/aseal.cpp.o
.PHONY : src/backend/aseal.cpp.o

src/backend/aseal.i: src/backend/aseal.cpp.i
.PHONY : src/backend/aseal.i

# target to preprocess a source file
src/backend/aseal.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fhel.dir/build.make CMakeFiles/fhel.dir/src/backend/aseal.cpp.i
.PHONY : src/backend/aseal.cpp.i

src/backend/aseal.s: src/backend/aseal.cpp.s
.PHONY : src/backend/aseal.s

# target to generate assembly for a file
src/backend/aseal.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fhel.dir/build.make CMakeFiles/fhel.dir/src/backend/aseal.cpp.s
.PHONY : src/backend/aseal.cpp.s

src/fhe.o: src/fhe.cpp.o
.PHONY : src/fhe.o

# target to build an object file
src/fhe.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fhel.dir/build.make CMakeFiles/fhel.dir/src/fhe.cpp.o
.PHONY : src/fhe.cpp.o

src/fhe.i: src/fhe.cpp.i
.PHONY : src/fhe.i

# target to preprocess a source file
src/fhe.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fhel.dir/build.make CMakeFiles/fhel.dir/src/fhe.cpp.i
.PHONY : src/fhe.cpp.i

src/fhe.s: src/fhe.cpp.s
.PHONY : src/fhe.s

# target to generate assembly for a file
src/fhe.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fhel.dir/build.make CMakeFiles/fhel.dir/src/fhe.cpp.s
.PHONY : src/fhe.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... clean-all"
	@echo "... uninstall"
	@echo "... example"
	@echo "... example64"
	@echo "... fhel"
	@echo "... libzstd_static"
	@echo "... minigzip"
	@echo "... minigzip64"
	@echo "... seal"
	@echo "... sealc"
	@echo "... zlib"
	@echo "... zlibstatic"
	@echo "... src/backend/aseal.o"
	@echo "... src/backend/aseal.i"
	@echo "... src/backend/aseal.s"
	@echo "... src/fhe.o"
	@echo "... src/fhe.i"
	@echo "... src/fhe.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

