name: fhel
description: |-
  Dart library for Fully Homomorphic Encryption that enables secure computation on encrypted data. 
  It exposes a set of basic functionalities for interacting with lower-level C FHE libraries, 
  allowing users to perform operations on sensitive data without exposing the underlying information. 
  The library is designed to be easy to use and efficient, making it suitable for a wide range of 
  applications in privacy-preserving computation.
version: 0.0.4
repository: https://github.com/jeffmur/fhel

environment:
  sdk: '>=3.1.5 <4.0.0'
  flutter: ">=1.20.0"

dependencies:
  ffi: ^2.1.0
  flutter:
    sdk: flutter
  path: ^1.8.3

dev_dependencies:
  flutter_lints: ^3.0.0
  test: ^1.24.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
