name: Build & Push Docker Image 🐳
description: Build and push a Docker image to a github container registry
inputs:
  image_name:
    description: 'The name of the image to build and push'
    default: 'ghcr.io/jeffmur/fhel'
  image_tag:
    description: 'The tag of the image to build and push'
    default: 'builder'
  dockerfile:
    description: 'Relative path to the Dockerfile, from root of the repository'
    default: 'Builder.Dockerfile'
  push:
    description: 'Whether to push the image to the registry'
    default: false
    type: boolean

runs:
  using: composite
  steps:
    - name: Checkout Repository 🛎️
      uses: actions/checkout@v4
      with:
        submodules: 'true'

    - name: Set up Docker Buildx 🧰
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry 🔒
      if: ${{ inputs.push == true }}
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Image 🐳
      uses: docker/build-push-action@v5
      with:
        push: ${{ inputs.push }}
        tags: ${{ inputs.image_name }}:${{ inputs.image_tag }}
        file: ${{ inputs.dockerfile }}
