name: SEAL 🧪

on: [push, pull_request]

env:
  IMAGE_NAME: ghcr.io/jeffmur/dart-fhe/seal

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    ## WORKAROUND ##
    # https://github.com/devcontainers/ci/issues/212
    - name: Workaround - Copy seal devcontainer
      run: |
        cp .devcontainer/seal/devcontainer.json .devcontainer/devcontainer.json
        cp .devcontainer/seal/Dockerfile .devcontainer/Dockerfile
    
    - name: Pre-build dev container image
      uses: devcontainers/ci@v0.3
      with:
        imageName: $IMAGE_NAME
        cacheFrom: $IMAGE_NAME
        push: always

    - name: Run make ci-build in dev container
      uses: devcontainers/ci@v0.3
      with:
        cacheFrom: $IMAGE_NAME
        push: never
        runCmd: dart test test/fhe_test.dart
